from decimal import Decimal

def quot2(dividend: Decimal, divisor: Decimal) -> Decimal: ...
def mod2(dividend: Decimal, divisor: Decimal) -> Decimal: ...
def quot3(value: Decimal, low: Decimal, high: Decimal) -> Decimal: ...
def mod3(value: Decimal, low: Decimal, high: Decimal) -> Decimal: ...
def max_day_in_month(year: Decimal, month: Decimal) -> Decimal: ...
