from isoduration.parser.exceptions import IncorrectDesignator as IncorrectDesignator, NoTime as NoTime, OutOfDesignators as OutOfDesignators, UnknownToken as UnknownToken, UnparseableValue as UnparseableValue
from isoduration.parser.util import is_letter as is_letter, is_number as is_number, is_time as is_time, is_week as is_week, parse_designator as parse_designator
from isoduration.types import DateDuration as DateDuration, Duration as Duration, TimeDuration as TimeDuration

def parse_datetime_duration(duration_str: str, sign: int) -> Duration: ...
def parse_date_duration(date_str: str, sign: int) -> Duration: ...
def parse_time_duration(time_str: str, sign: int) -> TimeDuration: ...
