from isoduration.formatter.exceptions import DurationFormattingException as DurationFormattingException
from isoduration.types import DateDuration as DateDuration, Duration as Duration

def check_global_sign(duration: Duration) -> int: ...
def validate_date_duration(date_duration: DateDuration) -> None: ...
