name: publish-docs
on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.12']

    steps:

    - uses: actions/checkout@v4

    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install hatch
      run: |
        pip install --upgrade pip
        pip install hatch

    - name: Install Graphviz
      run: sudo apt-get install graphviz graphviz-dev

    # caches the build docs
    # see https://squidfunk.github.io/mkdocs-material/plugins/requirements/caching/
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    - name: "Build and deploy docs to gh-pages"
      run: |
        hatch run docs:deploy
